### ISSUE TITLE
Indentation with spaces, not tabs.

### ISSUE THREAD

**Issue by Compyx** [Rhialto/twiXt#1]
Is it possible to use spaces for indentation in the generated file(s)? I tried `twixt -h/--help` but that gives me an error about `readline() on closed filehandle $file at ./twixt.pl line 88.`
I'm not much of a Perl hacker, so at that point I gave up ;)

I use 4 spaces per indentation level, so using tabs makes the output look very odd and ugly (in Vim I have tabstop=4, so stuff ends up indented wrong).

Cheers,
/Compyx

**Comment by Rhialto** [comment]
The spaces should be fixed via commit cdc6716,
I should add a -h option sometime :)
